CREATE TABLE IF NOT EXISTS drivers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  phone VARCHAR(15) UNIQUE NOT NULL,
  name VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fleet_pings (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  vehicle_id VARCHAR(50) NOT NULL CHECK (vehicle_id ~ '^[A-Za-z0-9_-]{1,50}$'),
  lat NUMERIC(9,6) NOT NULL CHECK (lat BETWEEN -90 AND 90),
  lng NUMERIC(9,6) NOT NULL CHECK (lng BETWEEN -180 AND 180),
  speed NUMERIC(5,2) NOT NULL CHECK (speed BETWEEN 0 AND 400),
  ts TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS fleet_pings_vehicle_ts_idx ON fleet_pings (vehicle_id, ts DESC);
